# Generated by Django 3.1 on 2021-02-11 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=20)),
                ('nickname', models.CharField(blank=True, db_index=True, max_length=10, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=13, unique=True)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'django'), (2, 'kakao')], default=1, null=True)),
                ('profile_pics', models.ImageField(default='default.jpg', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
