# Generated by Django 3.1 on 2021-06-19 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.URLField(null=True)),
                ('nickname', models.CharField(db_index=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrew_at', models.DateTimeField(null=True)),
                ('point', models.IntegerField(default=0, null=True)),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, '같구초보'), (2, '같구중수'), (3, '같구고수'), (4, '같구마스터')], default=1, null=True)),
                ('trading_address', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
