# Generated by Django 3.1 on 2021-02-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='area',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pics',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_snu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='withdrew_at',
            field=models.DateTimeField(null=True),
        ),
    ]
