# Generated by Django 3.1 on 2021-03-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailProfile',
        ),
    ]
