# Generated by Django 3.1 on 2021-02-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='area',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pics',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='withdrew_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'django'), (2, 'kakao'), (3, 'google')], default=1, null=True),
        ),
    ]
