# Generated by Django 3.1 on 2021-06-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '같구초보'), (2, '같구중수'), (3, '같구고수'), (4, '같구마스터')], default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trading_place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
