# Generated by Django 3.1 on 2021-06-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210603_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '같구초보'), (2, '같구중수'), (3, '같구고수'), (4, '같구마스터')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='point',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
