# Generated by Django 3.1 on 2021-06-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210604_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='trading_place',
            new_name='trading_address',
        ),
    ]
