# Generated by Django 3.1 on 2021-02-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210216_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_certificated', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_snu',
        ),
    ]
