# Generated by Django 3.1 on 2021-02-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210222_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(db_index=True, max_length=13, unique=True),
        ),
    ]
