# Generated by Django 3.1 on 2021-02-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
