# Generated by Django 3.1 on 2021-02-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210223_0553'),
        ('user', '0007_remove_userprofile_phone'),
        ('user', '0004_auto_20210225_1509'),
    ]

    operations = [
    ]
