# Generated by Django 3.1 on 2021-03-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_merge_20210227_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailprofile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='emailprofile',
            name='is_certificated',
        ),
        migrations.AlterField(
            model_name='emailprofile',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
