# Generated by Django 3.1 on 2021-02-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_merge_20210226_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
