# Generated by Django 3.1 on 2021-03-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210228_1125'),
        ('user', '0009_auto_20210301_1052'),
    ]

    operations = [
    ]
