# Generated by Django 3.1 on 2021-03-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210301_0938'),
        ('user', '0009_auto_20210228_1125'),
    ]

    operations = [
    ]
