# Generated by Django 3.1 on 2021-07-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0003_keyword_userkeyword'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userkeyword',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userkeyword',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='userkeyword',
            name='user',
        ),
        migrations.AddField(
            model_name='userfcmtoken',
            name='keyword',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='KeyWord',
        ),
        migrations.DeleteModel(
            name='UserKeyWord',
        ),
    ]
