# Generated by Django 3.1 on 2021-03-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210301_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderchat',
            name='cur_people',
        ),
        migrations.RemoveField(
            model_name='orderchat',
            name='required_people',
        ),
    ]
