# Generated by Django 3.1 on 2021-03-18 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20210309_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchat',
            name='participants',
            field=models.ManyToManyField(related_name='order_chat', through='chat.ParticipantProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
