# Generated by Django 3.1 on 2021-03-03 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20210301_0744'),
        ('chat', '0002_auto_20210302_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderchat',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_chat', to='article.article'),
        ),
        migrations.AlterField(
            model_name='orderchat',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'WAITING_MEMBERS'), (2, 'MEMBER_ASSEMBLED'), (3, 'PAY_STATUS_CHECKED'), (4, 'ORDER_COMPLETE'), (5, 'WAITING_PARCELS'), (6, 'WAITING_SHARE'), (7, 'GATGU_COMPLETE')], default=1),
        ),
        migrations.AlterField(
            model_name='orderchat',
            name='tracking_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
