# Generated by Django 3.1 on 2021-06-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210618_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderchat',
            name='participants',
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
