# Generated by Django 3.1 on 2021-06-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210620_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='media',
        ),
        migrations.CreateModel(
            name='ChatMessageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(blank=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='chat.chatmessage')),
            ],
        ),
    ]
