# Generated by Django 3.1 on 2021-07-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210630_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='pay_status',
            field=models.IntegerField(choices=[(1, '입금 전 '), (2, '입금 확인요청'), (3, '입금 완료')], default=1),
        ),
    ]
