# Generated by Django 3.1 on 2021-07-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210630_0819'),
        ('chat', '0005_auto_20210630_0322'),
    ]

    operations = [
    ]
