# Generated by Django 3.1 on 2021-08-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210725_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderchat',
            name='order_status',
        ),
    ]
