# Generated by Django 3.1 on 2021-06-17 11:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('article_status', models.PositiveSmallIntegerField(choices=[(1, '모집중'), (2, '모집완료'), (3, '거래완료'), (4, '기간만료')], db_index=True, default=1)),
                ('description', models.TextField()),
                ('trading_place', models.CharField(max_length=50)),
                ('product_url', models.CharField(max_length=200)),
                ('image', models.URLField(null=True)),
                ('price_min', models.PositiveIntegerField(default=0)),
                ('tag', models.PositiveSmallIntegerField(choices=[(1, '식품/배달음식'), (2, '디지털/가구/인테리어'), (3, '육아'), (4, '생활/화장품'), (5, '취미'), (6, '의류/악세사리'), (7, '반려동물용품'), (8, '음반/티켓/도서'), (9, '식물'), (10, '기타물품')], null=True)),
                ('time_in', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('written_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
