# Generated by Django 3.1 on 2021-02-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price_min',
            field=models.PositiveIntegerField(),
        ),
    ]
