# Generated by Django 3.1 on 2021-03-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
