# Generated by Django 3.1 on 2021-06-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='location',
            new_name='trading_place',
        ),
        migrations.RemoveField(
            model_name='article',
            name='need_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='people_min',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='article',
            name='article_status',
            field=models.PositiveSmallIntegerField(choices=[(1, '모집중'), (2, '모집완료'), (3, '거래완료'), (4, '기간만료')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='time_in',
            field=models.DateField(null=True),
        ),
    ]
