# Generated by Django 3.1 on 2021-06-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210608_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
