# Generated by Django 3.1 on 2021-02-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210224_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time_max',
        ),
        migrations.RemoveField(
            model_name='article',
            name='time_remaining',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='tag_used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='time_in',
            field=models.DurationField(null=True),
        ),
    ]
