# Generated by Django 3.1 on 2021-02-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210219_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='people_count_min',
            new_name='people_min',
        ),
    ]
