# Generated by Django 3.1 on 2021-06-09 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210608_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_in',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
