# Generated by Django 3.1 on 2021-02-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210228_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='written_at',
        ),
    ]
