# Generated by Django 3.1 on 2021-06-15 09:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210609_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AlterField(
            model_name='article',
            name='price_min',
            field=models.PositiveIntegerField(default=0, help_text='글 작성자가 자신이 원하는 금액을 제외한 금액을 모집글에 작성한다.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='product_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='time_in',
            field=models.DateField(default=datetime.date.today, help_text='7일 후를 기본값으로 가진다.', verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, choices=[('식품/배달음식', '식품/배달음식'), ('디지털/가구/인테리어', '디지털/가구/인테리어'), ('육아', '육아'), ('생활/화장품', '생활/화장품'), ('취미', '취미'), ('의류/악세사리', '의류/악세사리'), ('반려동물용품', '반려동물용품'), ('음반/티켓/도서', '음반/티켓/도서'), ('식물', '식물'), ('기타물품', '기타물품')], max_length=50)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articletag_images', to='article.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleimage_images', to='article.article')),
            ],
        ),
    ]
