# Generated by Django 3.1 on 2021-03-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210228_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='written_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
