# Generated by Django 3.1 on 2021-06-17 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210616_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('식품/배달음식', '식품/배달음식'), ('디지털/가구/인테리어', '디지털/가구/인테리어'), ('육아', '육아'), ('생활/화장품', '생활/화장품'), ('취미', '취미'), ('의류/악세사리', '의류/악세사리'), ('반려동물용품', '반려동물용품'), ('음반/티켓/도서', '음반/티켓/도서'), ('식물', '식물'), ('기타물품', '기타물품')], max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='articletag',
            name='tag',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='article.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='articletag',
            unique_together={('article', 'tag')},
        ),
        migrations.RemoveField(
            model_name='articletag',
            name='tag_name',
        ),
    ]
