# Generated by Django 3.1 on 2021-06-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20210617_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
