# Generated by Django 3.1 on 2021-06-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20210618_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='img',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
