# Generated by Django 3.1 on 2021-07-16 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20210621_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_in',
            field=models.DateTimeField(default=datetime.date.today, help_text='7일 후를 기본값으로 가진다.', verbose_name='Date'),
        ),
    ]
