# Generated by Django 3.1 on 2021-07-19 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20210716_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 17, 57, 28, 730761)),
        ),
    ]
