# Generated by Django 3.1 on 2021-07-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20210722_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_in',
            field=models.DateTimeField(null=True),
        ),
    ]
