# Generated by Django 3.1 on 2021-07-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20210719_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_in',
            field=models.DateTimeField(null=True),
        ),
    ]
