# Generated by Django 3.1 on 2021-07-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20210727_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='img_url',
            field=models.TextField(default='dafault'),
        ),
    ]
