# Generated by Django 3.1 on 2021-09-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20210731_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_status',
            field=models.PositiveSmallIntegerField(choices=[(1, '모집중'), (2, '거래중'), (3, '거래완료'), (4, '기간만료')], db_index=True, default=1),
        ),
    ]
