# Generated by Django 3.1 on 2021-07-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='reporter',
        ),
        migrations.DeleteModel(
            name='ReportComment',
        ),
    ]
