# Generated by Django 3.1 on 2021-07-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210714_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='updated_at',
            new_name='resolved_at',
        ),
    ]
