# Generated by Django 3.1 on 2021-07-21 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0014_auto_20210721_2119'),
        ('report', '0003_auto_20210719_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='resolved_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='report',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='article.article'),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
